import Head from "next/head";
import Layout from "../components/layout/Layout";
import styles from "../styles/Home.module.css";
import PrimaryButton from "../components/resources/buttons/PrimaryButton";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}></main>
        <PrimaryButton color="error" /> 
      </Layout>
    </div>
  );
}
