import Head from "next/head";
import Layout from "../components/layout/Layout";
import PrimaryButton from "../components/resources/buttons/PrimaryButton";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="px-2">
        <PrimaryButton>hola</PrimaryButton> 
        </main>
      </Layout>
    </div>
  );
}
